goprint/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

urlpatterns = [
    path('printcenter.geojson', views.PrintCenterMapData.as_view(), name="printcenter_data"),

    path('print-center/add/', views.PrintCenterCreateView.as_view(), name='printcenter_add'),
    path('print-center/<int:pk>/prices/', views.PrintCenterPriceListView.as_view(), name='printcenter_prices'),
    path('print-center/<int:pk>/update/', views.PrintCenterUpdateView.as_view(), name='printcenter_update'),
    path('print-center/<int:pk>/', views.PrintCenterDetailView.as_view(), name='printcenter_detail'),
    path('print-center', views.PrintCenterListView.as_view(), name='printcenter_list'),

    path('order/add/<int:printcenter_id>/', views.OrderCreateView.as_view(), name='order_add'),
    path('order/<int:pk>/', views.OrderDetailView.as_view(), name='order_detail'),
    path('order/', views.OrderListView.as_view(), name='order_list'),

    path('print-centers-cmplt/', views.PrintCenterAutocomplete.as_view(), name='print_center_cmplt'),
    path('price-cmplt/', views.PriceAutocomplete.as_view(), name='price_cmplt'),

    path('<slug:city>/', views.PrintCenterMap.as_view(), name="printcenter_map"),
    path('', TemplateView.as_view(template_name='goprint/printcenter_landing.html')),
]

web/urls.py
from django.urls import include, path
from django.contrib import admin
from django.contrib.auth import views as auth_views


admin.autodiscover()
urlpatterns = [
    path('accounts/', include('registration.backends.hmac.urls')),
    path('accounts/login', auth_views.LoginView.as_view(), name='login'),
    path('accounts/logout', auth_views.LogoutView.as_view(), name='logout'),
    path('accounts/', include('registration.backends.hmac.urls')),
    # url(r'^admin/', include(admin.site.urls)),
    # url(r'^social/', include('social_django.urls', namespace='social')),
    path('admin/', admin.site.urls),
    path('', include(('goprint.urls', 'goprint'), namespace='goprint')),
]

goprint/models.py
from django.urls import reverse
from django.contrib.auth.models import User
from django.contrib.gis.db import models


class PrintCenter(models.Model):
    """Print center model."""
    address = models.CharField('Address', max_length=150)
    name = models.CharField('Name', max_length=50)
    point = models.PointField('Geo Coordinates')
    owner = models.ForeignKey(User, on_delete=models.CASCADE, null=True,
                              related_name='User_Owner_PrintCenter')
    registered_at = models.DateTimeField('registration date', auto_now_add=True)

    @property
    def detail_url(self):
        return reverse('goprint:printcenter_detail', kwargs={'pk': self.id})

    @property
    def document_submit_url(self):
        return reverse('goprint:order_add', kwargs={'printcenter_id': self.id})

    def __str__(self):
        return "[" + self.name + "] " + self.address


class Document(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    file = models.FileField(upload_to='files/%Y/%m/%d')
    create_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        user_name = 'null' if self.user is None else self.user.username
        return str(self.file) + " [" + user_name + "]"


class Price(models.Model):
    print_center = models.ForeignKey(PrintCenter, on_delete=models.CASCADE, null=True)
    name = models.CharField('Service Name', max_length=200)
    price = models.DecimalField('Service Price', max_digits=4, decimal_places=2)
    edit_at = models.DateTimeField('last edit date', auto_now=True)

    def __str__(self):
        return self.name + " [" + str(self.price) + "]"


class Order(models.Model):
    document = models.ForeignKey(Document, on_delete=models.CASCADE)
    price = models.ForeignKey(Price, on_delete=models.CASCADE)
    create_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.create_at) + " [" + str(self.price) + "]"


class Feedback(models.Model):
    print_center = models.ForeignKey(PrintCenter, on_delete=models.CASCADE)
    message = models.CharField('Address', max_length=1000)
    rating = models.IntegerField('Rating')

goprint/forms.py
from django.contrib.gis import forms
from dal_select2 import widgets
from .models import PrintCenter, Order, Document


class PrintCenterForm(forms.ModelForm):
    class Meta:
        model = PrintCenter
        exclude = ('owner', 'registrator',)
        owner = forms.CharField(widget=forms.HiddenInput(), required=False)
        registrator = forms.CharField(widget=forms.HiddenInput(), required=False)
        widgets = {
            'point': forms.OSMWidget(
                attrs={
                    'map_width': 800,
                    'map_height': 500,
                    'default_lat': 49.93,
                    'default_lon': 36.18,
                }
            )
        }


class NaiveOrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = '__all__'


class OrderForm(forms.Form):
    document_file = forms.FileField()
    print_center = forms.CharField(widget=forms.HiddenInput())
    price = forms.CharField(
        widget=widgets.ListSelect2('goprint:price_cmplt',
        forward=('print_center',)))


class DocumentForm(forms.ModelForm):
    class Meta:
        model = Document
        exclude = ('user',)

goprint/views/common.py
from goprint.models import PrintCenter

city_map_settings = {
    'kharkiv': {'DEFAULT_CENTER': (49.9898255, 36.2312968), 'DEFAULT_ZOOM': 13},
    'kyiv': {'DEFAULT_CENTER': (50.4387008, 30.4778504), 'DEFAULT_ZOOM': 12}
}


class MapSettingsContextMixin:
    def get_context_data(self, **kwargs):
        context = {}
        if 'city' in kwargs:
            self.request.session['city'] = kwargs['city'].lower()

        city_name = context['city'] = self.request.session['city']
        if city_name is None:
            raise ValueError('"city" not defined')

        context['map_settings'] = kwargs['map_settings'] if 'map_settings' in kwargs else {}
        if city_name in city_map_settings:
            context['map_settings'] = {**city_map_settings[city_name], **context['map_settings']}
            if 'map_settings' in kwargs:
                del kwargs['map_settings']

        context.update(kwargs)
        return super().get_context_data(**context)


class PrintCenterGetterMixin:
    def get_user_printcenter(self):
        return PrintCenter.objects \
            .order_by('registered_at') \
            .filter(owner=self.request.user) \
            .first()


class PrintCenterRoleContextMixin(PrintCenterGetterMixin):
    def get(self, request, *args, **kwargs):
        if self.extra_context is None:
            self.extra_context = {}

        # TODO: use values() method to get only few columns
        self.extra_context['user_printcenter'] = self.get_user_printcenter()

        return super().get(request, *args, **kwargs)

goprint/views/order_view_set.py
from django.db.models import Prefetch
from django.urls import reverse
from django.views.generic import FormView, ListView, DetailView

from goprint.forms import OrderForm
from goprint.models import Document, Price, Order
from goprint.views.common import MapSettingsContextMixin


class OrderCreateView(FormView):
    form_class = OrderForm
    template_name = 'goprint/order_create.html'

    def get_success_url(self):
        return reverse('goprint:order_list')

    def form_valid(self, form):
        document = Document.objects.create(file=form.cleaned_data['document_file'], user=self.request.user)
        document.save()
        price = Price.objects.get(id=form.cleaned_data['price'])
        if price.print_center.id != self.kwargs['printcenter_id']:
            raise Exception('incorrect princenter_id')

        order = Order.objects.create(document=document, price=price)
        order.save()
        return super().form_valid(form)

    def get_initial(self):
        initial = super().get_initial()
        initial['print_center'] = self.kwargs['printcenter_id']

        return initial

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['printcenter_id'] = self.kwargs['printcenter_id']
        return context


class OrderListView(MapSettingsContextMixin, ListView):
    def get_queryset(self):
        return Order.objects.prefetch_related('price')\
            .filter(document__user=self.request.user)


class OrderDetailView(MapSettingsContextMixin, DetailView):
    model = Order

goprint/views/price_views.py
from dal import autocomplete
from django.views.generic import ListView

from goprint.models import Price


class PrintCenterPriceListView(ListView):
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['printcenter_pk'] = self.kwargs['pk']
        return context

    def get_queryset(self):
        return Price.objects.filter(print_center__pk=self.kwargs['pk'])


class PriceAutocomplete(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        qs = Price.objects.all()
        print_center = self.forwarded.get('print_center', None)

        if print_center:
            qs = qs.filter(print_center=print_center)

        if self.q:
            qs = qs.filter(name__istartswith=self.q)

        return qs

goprint/views/print_center_views.py
from dal import autocomplete
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Prefetch
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy, reverse
from django.views.generic import FormView, ListView, DetailView, TemplateView, UpdateView
from djgeojson.views import GeoJSONLayerView

from goprint.forms import PrintCenterForm
from goprint.models import PrintCenter
from goprint.views.common import MapSettingsContextMixin, PrintCenterRoleContextMixin, PrintCenterGetterMixin


class PrintCenterMap(PrintCenterRoleContextMixin, MapSettingsContextMixin, LoginRequiredMixin, TemplateView):
    login_url = reverse_lazy('login')
    template_name = 'goprint/printcenter_map.html'


class PrintCenterMapData(LoginRequiredMixin, GeoJSONLayerView):
    login_url = reverse_lazy('login')
    model = PrintCenter
    geometry_field = 'point'
    properties = {'name': 'title', 'detail_url': 'detailUrl', 'document_submit_url': 'documentSubmitUrl'}


class PrintCenterCreateView(MapSettingsContextMixin, PrintCenterGetterMixin, LoginRequiredMixin, FormView):
    login_url = reverse_lazy('login')
    form_class = PrintCenterForm
    template_name = 'goprint/printcenter_create.html'
    user_printcenter = None

    def _redirect_to_detail(self):
        return HttpResponseRedirect(reverse('goprint:printcenter_detail', kwargs={"pk": self.user_printcenter.id}))

    def get(self, request, *args, **kwargs):
        self.user_printcenter = self.get_user_printcenter()
        if self.user_printcenter is not None:
            return self._redirect_to_detail()

        return super().get(request, *args, **kwargs)

    def form_valid(self, form):
        self.user_printcenter = self.get_user_printcenter()
        if self.user_printcenter is not None:
            return self._redirect_to_detail()

        model = form.save(commit=False)
        model.registrator = self.request.user
        model.owner = self.request.user
        model.address = form.cleaned_data['address']
        model.name = form.cleaned_data['name']
        model.point = form.cleaned_data['point']
        model.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('goprint:printcenter_list')


class PrintCenterUpdateView(MapSettingsContextMixin, PrintCenterGetterMixin, LoginRequiredMixin, UpdateView):
    login_url = reverse_lazy('login')
    form_class = PrintCenterForm
    model = PrintCenter
    template_name = 'goprint/printcenter_update.html'

    def _check_printcenter(self):
        return self.object.owner == self.request.user

    def get(self, request, *args, **kwargs):
        res = super().get(request, *args, **kwargs)
        if self._check_printcenter():
            return res
        return HttpResponseRedirect(reverse('goprint:printcenter_detail', kwargs=kwargs))

    def form_valid(self, form):
        model = form.save(commit=False)
        model.owner = self.request.user
        model.address = form.cleaned_data['address']
        model.name = form.cleaned_data['name']
        model.point = form.cleaned_data['point']
        model.save()
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        kwargs['pk'] = self.kwargs['pk']
        return super().get_context_data(**kwargs)

    def get_success_url(self):
        return reverse_lazy('goprint:printcenter_detail', kwargs={'pk': self.kwargs['pk']})


class PrintCenterListView(PrintCenterRoleContextMixin, LoginRequiredMixin, ListView):
    login_url = reverse_lazy('login')
    model = PrintCenter


class PrintCenterDetailView(MapSettingsContextMixin, PrintCenterRoleContextMixin, LoginRequiredMixin, DetailView):
    login_url = reverse_lazy('login')
    form = PrintCenterForm

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        map_settings = {
            'DEFAULT_ZOOM': 16,
            'DEFAULT_CENTER': self.object.point.tuple[::-1]
        }
        context = self.get_context_data(object=self.object, map_settings=map_settings)
        return self.render_to_response(context)

    def get_queryset(self):
        queryset = PrintCenter.objects.all()
        PrintCenter.objects.prefetch_related(Prefetch('price_set', queryset=queryset))
        return queryset


class PrintCenterAutocomplete(LoginRequiredMixin, autocomplete.Select2QuerySetView):
    login_url = reverse_lazy('login')

    def get_queryset(self):
        qs = PrintCenter.objects.all()

        if self.q:
            qs = qs.filter(name__istartswith=self.q)

        return qs

goprint/templates/goprint/map_menu.html
<h1>Принтцентры в городе</h1>
<div>
    <ul>
        {# top N city #}
        <li><a href="{% url 'goprint:printcenter_map' 'kyiv' %}">Kyiv</a></li>
        <li><a href="{% url 'goprint:printcenter_map' 'kharkiv' %}">Kharkiv</a></li>
    </ul>
    <ul>
        <li><a href="{% url 'goprint:order_list' %}">[Мои заявки на печать]</a></li>
    </ul>

    <ul>
        <li><a href="{% url 'goprint:printcenter_list' %}">[Список принтцентров]</a></li>
        {% if user_printcenter %}
            <li><a href="{% url 'goprint:printcenter_detail' user_printcenter.id %}">[Мой принтцентр]</a></li>
        {% else %}
            <li><a href="{% url 'goprint:printcenter_add' %}">[Добавить принтцентр]</a></li>
        {% endif %}
    </ul>
</div>

goprint/templates/goprint/order_create.html
{% extends 'goprint/base.html' %}
{% load static %}

{% block extrahead %}
    <script type="text/javascript" src="{% static '/js/jquery-3.0.0.min.js' %} "></script>
    {{ form.media }}
{% endblock %}

{% block content %}
<form method="POST" action="{% url 'goprint:order_add' printcenter_id %}" enctype="multipart/form-data">
    <div class="card-title">Заявка на печать</div>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="отправить заявку"/>
</form>
{% endblock %}

goprint/templates/goprint/order_detail.html
{% extends 'goprint/base.html' %}

{% block content %}
    <h1>Order {{ object }}</h1>

    <a href="{% url 'goprint:order_list' %}">назад</a>
{% endblock %}

goprint/templates/goprint/order_list.html
{% extends 'goprint/base.html' %}

{% block content %}
    <h1>Orders</h1>
    <ul>
    {% for order in object_list %}
        <li>{{ order }} <a href="{% url 'goprint:order_detail' order.pk %}">more</a> </li>
    {% empty %}
        <li>No articles yet.</li>
    {% endfor %}
    </ul>
    <p>
        <a href="{% url 'goprint:printcenter_map' city %}">На карту</a>
    </p>
{% endblock %}

goprint/templates/goprint/price_list.html
{% extends 'goprint/base.html' %}

{% block content %}
    <h1>Orders</h1>
    <ul>
    {% for price in object_list %}
        <li>{{ price }}</li>
    {% empty %}
        <li>No articles yet.</li>
    {% endfor %}
    </ul>

    <a href="{% url 'goprint:printcenter_detail' printcenter_pk %}">назад в принтцентр</a>
{% endblock %}

goprint/templates/goprint/printcenter_create.html
{% extends 'goprint/base.html' %}

{% block extrahead %}
    {{ form.media }}
{% endblock %}

{% block content %}
<div >
    <form method="POST" action="{% url 'goprint:printcenter_add' %}" enctype="multipart/form-data">
        <div class="card-title">Принт центр</div>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="отправить заявку"/>
        <a href="{% url 'goprint:printcenter_map' city %}">на карту</a>
    </form>
</div>

{% endblock %}

goprint/templates/goprint/printcenter_detail.html
{% extends 'goprint/base.html' %}
{% load leaflet_tags %}
{% load static %}

{% block extrahead %}
    {% leaflet_js %}
    {% leaflet_css %}
    <style>
      /* next line is usefull for production mode */
      .leaflet-default-icon-path { background-image: url("/static/leaflet/images/marker-icon.png") !important ; }
    </style>

{% endblock %}

{% block content %}
    <h1>Принтцентр: {{ object.name }}</h1>
    <h3>Aдрес: {{ object.address }} </h3>
    {% leaflet_map "main" settings_overrides=map_settings %}
    {{ object.point }}
    <table>
    {% with prices=object.price_set.all %}
        <tr><th>услуга</th><th>цена (грн)</th></tr>
        {% for price in prices %}
        <tr><td>{{ price.name }}</td><td>{{ price.price }}</td></tr>
        {% endfor %}
    {% endwith %}
    </table>
    <p>
        {% ifequal user_printcenter.id object.pk %}
            <a href="{% url 'goprint:printcenter_update' object.pk %}"> редактировать описание </a>
        {% else %}
            <a href="{% url 'goprint:order_add' object.pk %}"> оформить заказ на печать </a>
        {% endifequal %}
    </p>
    <p>
        <a href="{% url 'goprint:printcenter_map' city %}">На карту</a>
    </p>
{% endblock %}

{% block extrajs %}
<script type="text/javascript">
 window.addEventListener("map:init", function (e) {
    var detail = e.detail;
    L.marker([{{ object.point.y }},{{ object.point.x }}]).addTo(detail.map);
}, false);
 </script>
{% endblock %}

goprint/templates/goprint/printcenter_landing.html
{% extends 'goprint/base.html' %}

{% block content %}
    <h1>Printcenter Spots</h1>
<ul>
    <li><a href="{% url 'goprint:printcenter_map' 'kyiv' %}">Kyiv</a></li>
    <li><a href="{% url 'goprint:printcenter_map' 'kharkiv' %}">Kharkiv</a></li>
</ul>

{% endblock %}

goprint/templates/goprint/printcenter_list.html
{% extends 'goprint/base.html' %}

{% block content %}
    <h1>Printcenters</h1>
    <ul>
    {% for printcenter in object_list %}
        <li>{{ printcenter }} <a href="{% url 'goprint:printcenter_detail' printcenter.pk %}">more</a> </li>
    {% empty %}
        <li>No articles yet.</li>
    {% endfor %}
    </ul>

    {% if user_printcenter %}
        <li><a href="{% url 'goprint:printcenter_detail' user_printcenter.id %}">[Мой принтцентр]</a></li>
    {% else %}
        <li><a href="{% url 'goprint:printcenter_add' %}">[Добавить принтцентр]</a></li>
    {% endif %}

{% endblock %}

goprint/templates/goprint/printcenter_map.html
{% extends 'goprint/base.html' %}
{% load leaflet_tags %}
{% load static %}

{% block extrahead %}
    {% leaflet_js %}
    {% leaflet_css %}
    <style>
      .leaflet-container { height: 100%; }
      /* next line is usefull for production mode */
      .leaflet-default-icon-path { background-image: url("/static/leaflet/images/marker-icon.png") !important ; }
    </style>

{% endblock %}

{% block content %}
    {% include "goprint/map_menu.html" %}

    {% leaflet_map "main" settings_overrides=map_settings %}
{% endblock %}

{% block extrajs %}
    <script type="text/javascript">
      var dataurl = '{% url "goprint:printcenter_data" %}';
      window.addEventListener("map:init", function (event) {
        var map = event.detail.map;
        // Download GeoJSON data with Ajax
        fetch(dataurl)
          .then(function(resp) {
            return resp.json();
          })
          .then(function(data) {
            L.geoJson(data, {
              onEachFeature: function onEachFeature(feature, layer) {
                var props = feature.properties;
                var content = `<h3>принтцентр <a href="${props.detailUrl}">${props.title}</a></h3><p><a href="${props.documentSubmitUrl}">[добавить на печать]</a></p>`;
                layer.bindPopup(content);
            }}).addTo(map);
          });
      });
    </script>
{% endblock %}

goprint/templates/goprint/printcenter_update.html
{% extends 'goprint/base.html' %}

{% block extrahead %}
    {{ form.media }}
{% endblock %}

{% block content %}
    <h1>Редактировать Printcenter {{ object.name }}</h1>

    <div >
    <form method="POST" action="{% url 'goprint:printcenter_update' pk %}" enctype="multipart/form-data">
        <div class="card-title">Принт центр</div>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Применить"/>
        <a href="{% url 'goprint:printcenter_map' city %}">на карту</a>
    </form>
</div>

{% endblock %}